export const hollandQuestions = [
    // R - Realistic (12 câu)
    {id: 1, text: "Tôi thích sửa chữa máy móc", type: "R"},
    {id: 2, text: "Tôi thích vận hành máy móc", type: "R"},
    {id: 3, text: "Tôi thích xây dựng, lắp ráp", type: "R"},
    {id: 4, text: "Tôi thích làm việc ngoài trời", type: "R"},
    {id: 5, text: "Tôi thích vận động thể chất", type: "R"},
    {id: 6, text: "Tôi thích lái xe hoặc thiết bị cơ khí", type: "R"},
    {id: 7, text: "Tôi thích dùng công cụ, thiết bị", type: "R"},
    {id: 8, text: "Tôi thích thể hiện kỹ năng thực hành", type: "R"},
    {id: 9, text: "Tôi thích chăm sóc động vật hoặc cây cối", type: "R"},
    {id: 10, text: "Tôi thích sửa chữa đồ vật", type: "R"},
    {id: 11, text: "Tôi thích thử thách kỹ thuật", type: "R"},
    {id: 12, text: "Tôi thích làm việc cần sức mạnh hoặc kỹ năng tay chân", type: "R"},

    // I - Investigative (12 câu)
    {id: 13, text: "Tôi thích tìm hiểu các lý thuyết", type: "I"},
    {id: 14, text: "Tôi thích nghiên cứu, phân tích vấn đề", type: "I"},
    {id: 15, text: "Tôi thích giải quyết vấn đề trừu tượng", type: "I"},
    {id: 16, text: "Tôi thích học các môn khoa học", type: "I"},
    {id: 17, text: "Tôi thích suy nghĩ logic và phân tích", type: "I"},
    {id: 18, text: "Tôi thích thử nghiệm, nghiên cứu", type: "I"},
    {id: 19, text: "Tôi thích đọc sách về kiến thức chuyên môn", type: "I"},
    {id: 20, text: "Tôi thích giải quyết các bài toán khó", type: "I"},
    {id: 21, text: "Tôi thích dự đoán, kiểm chứng kết quả", type: "I"},
    {id: 22, text: "Tôi thích khám phá điều mới", type: "I"},
    {id: 23, text: "Tôi thích tìm hiểu nguyên nhân, kết quả", type: "I"},
    {id: 24, text: "Tôi thích phân tích thông tin, dữ liệu", type: "I"},

    // A - Artistic (12 câu)
    {id: 25, text: "Tôi thích vẽ, tạo hình", type: "A"},
    {id: 26, text: "Tôi thích viết lách, sáng tác", type: "A"},
    {id: 27, text: "Tôi thích biểu diễn nghệ thuật", type: "A"},
    {id: 28, text: "Tôi thích trang trí, thiết kế", type: "A"},
    {id: 29, text: "Tôi thích thể hiện sáng tạo", type: "A"},
    {id: 30, text: "Tôi thích âm nhạc, nhảy múa", type: "A"},
    {id: 31, text: "Tôi thích làm phim, quay video", type: "A"},
    {id: 32, text: "Tôi thích thiết kế đồ họa", type: "A"},
    {id: 33, text: "Tôi thích tạo ra điều mới mẻ", type: "A"},
    {id: 34, text: "Tôi thích thử các phong cách nghệ thuật", type: "A"},
    {id: 35, text: "Tôi thích biểu đạt cảm xúc qua nghệ thuật", type: "A"},
    {id: 36, text: "Tôi thích sáng tạo các ý tưởng mới", type: "A"},

    // S - Social (12 câu)
    {id: 37, text: "Tôi thích giúp đỡ người khác", type: "S"},
    {id: 38, text: "Tôi thích chăm sóc, tư vấn người khác", type: "S"},
    {id: 39, text: "Tôi thích tham gia các hoạt động cộng đồng", type: "S"},
    {id: 40, text: "Tôi thích dạy học, hướng dẫn người khác", type: "S"},
    {id: 41, text: "Tôi thích hỗ trợ mọi người hoàn thành công việc", type: "S"},
    {id: 42, text: "Tôi thích làm việc nhóm", type: "S"},
    {id: 43, text: "Tôi thích lắng nghe người khác", type: "S"},
    {id: 44, text: "Tôi thích chăm sóc người yếu thế", type: "S"},
    {id: 45, text: "Tôi thích giải thích, hướng dẫn chi tiết", type: "S"},
    {id: 46, text: "Tôi thích tham gia các hoạt động xã hội", type: "S"},
    {id: 47, text: "Tôi thích tư vấn hoặc hỗ trợ người khác", type: "S"},
    {id: 48, text: "Tôi thích giúp mọi người cải thiện kỹ năng", type: "S"},

    // E - Enterprising (12 câu)
    {id: 49, text: "Tôi thích kinh doanh, quản lý", type: "E"},
    {id: 50, text: "Tôi thích dẫn dắt người khác", type: "E"},
    {id: 51, text: "Tôi thích thuyết phục, bán hàng", type: "E"},
    {id: 52, text: "Tôi thích lãnh đạo nhóm", type: "E"},
    {id: 53, text: "Tôi thích tổ chức, quản lý dự án", type: "E"},
    {id: 54, text: "Tôi thích khởi nghiệp hoặc thử thách mới", type: "E"},
    {id: 55, text: "Tôi thích thuyết trình, nói trước đám đông", type: "E"},
    {id: 56, text: "Tôi thích thương thuyết, đàm phán", type: "E"},
    {id: 57, text: "Tôi thích đảm nhận trách nhiệm lớn", type: "E"},
    {id: 58, text: "Tôi thích khích lệ người khác đạt mục tiêu", type: "E"},
    {id: 59, text: "Tôi thích thử thách bản thân trong công việc", type: "E"},

    // C - Conventional (12 câu)
    {id: 60, text: "Tôi thích sắp xếp, ghi chép, kiểm tra", type: "C"},
    {id: 61, text: "Tôi thích quản lý hồ sơ, dữ liệu", type: "C"},
    {id: 62, text: "Tôi thích làm việc có trật tự", type: "C"},
    {id: 63, text: "Tôi thích tuân thủ quy trình", type: "C"},
    {id: 64, text: "Tôi thích làm việc văn phòng, máy tính", type: "C"},
    {id: 65, text: "Tôi thích tính toán, ghi chép chi tiết", type: "C"},
    {id: 66, text: "Tôi thích lập báo cáo, sổ sách", type: "C"},
    {id: 67, text: "Tôi thích làm việc theo kế hoạch", type: "C"},
    {id: 68, text: "Tôi thích tổ chức dữ liệu, lưu trữ", type: "C"},
    {id: 69, text: "Tôi thích tuân thủ hướng dẫn", type: "C"},
    {id: 70, text: "Tôi thích làm việc chính xác, cẩn thận", type: "C"},
    {id: 71, text: "Tôi thích kiểm tra, rà soát chi tiết", type: "C"},
    {id: 72, text: "Tôi thích làm việc theo quy tắc rõ ràng", type: "C"},
];
