export const hollandCareers = [
    {
        id: 1,
        name: 'Công nghệ kỹ thuật số',
        description: 'Ngành liên quan đến công nghệ thông tin, phần mềm, trí tuệ nhân tạo và dữ liệu.',
        examples: ['Lập trình viên', 'Kỹ sư AI', 'Chuyên viên dữ liệu', 'Chuyên viên an ninh mạng'],
    },
    {
        id: 2,
        name: 'Kỹ thuật – Cơ khí – Tự động hóa',
        description: 'Thiết kế, chế tạo, vận hành và bảo trì các hệ thống kỹ thuật và máy móc.',
        examples: ['Kỹ sư điện', 'Kỹ sư ô tô', 'Kỹ sư robot', 'Công nghệ chế tạo máy'],
    },
    {
        id: 3,
        name: 'Nghệ thuật – Sáng tạo – Thiết kế',
        description: 'Thể hiện bản thân qua nghệ thuật và sáng tạo trong nhiều lĩnh vực.',
        examples: ['Thiết kế đồ họa', 'Thời trang', 'Nhiếp ảnh', 'Đạo diễn'],
    },
    {
        id: 4,
        name: 'Truyền thông – Quảng cáo – Nội dung số',
        description: 'Tạo, quản lý và truyền tải thông tin để xây dựng hình ảnh và thương hiệu.',
        examples: ['PR', 'Marketing', 'Biên tập viên', 'Sáng tạo nội dung'],
    },
    {
        id: 5,
        name: 'Xã hội – Giáo dục – Tâm lý',
        description: 'Hỗ trợ, giáo dục và phát triển con người trong cộng đồng.',
        examples: ['Giáo viên', 'Nhà tâm lý', 'Nhân viên xã hội', 'Cố vấn học đường'],
    },
    {
        id: 6,
        name: 'Kinh doanh – Quản lý – Khởi nghiệp',
        description: 'Lãnh đạo, điều hành và phát triển tổ chức hoặc doanh nghiệp.',
        examples: ['Quản trị kinh doanh', 'Startup', 'Quản lý nhân sự', 'Giám đốc dự án'],
    },
    {
        id: 7,
        name: 'Tài chính – Ngân hàng – Kế toán',
        description: 'Phân tích, quản lý và tối ưu hóa nguồn lực tài chính.',
        examples: ['Kế toán viên', 'Chuyên viên ngân hàng', 'Kiểm toán', 'Phân tích đầu tư'],
    },
    {
        id: 8,
        name: 'Thương mại – Marketing – Logistics',
        description: 'Vận hành chuỗi cung ứng, thị trường và hoạt động thương mại.',
        examples: ['Marketing', 'Thương mại điện tử', 'Logistics', 'Quản lý kho'],
    },
    {
        id: 9,
        name: 'Luật – Hành chính – Quản trị công',
        description: 'Giải quyết vấn đề pháp lý, chính sách và hoạt động công vụ.',
        examples: ['Luật sư', 'Công chức', 'Thanh tra', 'Quản trị hành chính'],
    },
    {
        id: 10,
        name: 'Nghiên cứu – Khoa học – Phân tích',
        description: 'Khám phá, phân tích và phát triển tri thức mới trong nhiều lĩnh vực.',
        examples: ['Nhà nghiên cứu', 'Nhà khoa học', 'Phân tích hệ thống', 'Nhà toán học'],
    },
    {
        id: 11,
        name: 'Nông nghiệp – Môi trường – Sinh học',
        description: 'Nghiên cứu, sản xuất và bảo tồn hệ sinh thái và tài nguyên thiên nhiên.',
        examples: ['Kỹ sư nông nghiệp', 'Kỹ sư môi trường', 'Nhà sinh học', 'Nông nghiệp công nghệ cao'],
    },
    {
        id: 12,
        name: 'Y – Dược – Sức khỏe',
        description: 'Chăm sóc, chữa bệnh và nâng cao sức khỏe con người.',
        examples: ['Bác sĩ', 'Dược sĩ', 'Điều dưỡng', 'Kỹ thuật viên y học'],
    },
    {
        id: 13,
        name: 'Du lịch – Nhà hàng – Khách sạn',
        description: 'Phục vụ, giao tiếp và mang đến trải nghiệm cho du khách.',
        examples: ['Hướng dẫn viên', 'Quản trị khách sạn', 'Quản lý nhà hàng', 'Tổ chức sự kiện'],
    },
    {
        id: 14,
        name: 'Công nghệ sáng tạo – Game – Đa phương tiện',
        description: 'Kết hợp công nghệ và sáng tạo để tạo ra sản phẩm giải trí và truyền thông.',
        examples: ['Nhà phát triển game', 'Animator', 'Kỹ xảo điện ảnh', 'Thiết kế UX/UI'],
    },
    {
        id: 15,
        name: 'Xây dựng – Kiến trúc – Quy hoạch',
        description: 'Thiết kế và xây dựng công trình, quy hoạch không gian sống.',
        examples: ['Kiến trúc sư', 'Kỹ sư xây dựng', 'Quy hoạch đô thị', 'Giám sát công trình'],
    },
    {
        id: 16,
        name: 'Khởi nghiệp – Đổi mới sáng tạo',
        description: 'Tạo ra giá trị mới thông qua ý tưởng, sản phẩm và mô hình kinh doanh mới.',
        examples: ['Nhà sáng lập startup', 'Giám đốc sản phẩm', 'Nhà đầu tư', 'Nhà phát minh'],
    },
    {
        id: 17,
        name: 'Ngoại ngữ – Quốc tế – Văn hóa',
        description: 'Giao lưu quốc tế, nghiên cứu và truyền bá văn hóa.',
        examples: ['Phiên dịch viên', 'Ngoại giao', 'Hướng dẫn viên quốc tế', 'Giảng viên ngoại ngữ'],
    },
    {
        id: 18,
        name: 'Công nghiệp – Sản xuất – Quản lý chất lượng',
        description: 'Tổ chức, vận hành và giám sát quy trình sản xuất và chất lượng sản phẩm.',
        examples: ['Kỹ sư công nghiệp', 'Quản lý sản xuất', 'Kiểm định chất lượng', 'Chuyên viên ISO'],
    },
];
